### ISSUE TITLE
Issues running it locally

### ISSUE THREAD

**Issue by ICreativeKid** [dKosarevsky/AI-Talks#16]
![Screenshot 2023-05-04 at 9 04 37 PM](https://user-images.githubusercontent.com/6654625/236359494-0620ff61-f6af-4ab0-bbbd-085c405fcf4e.png)
![Screenshot 2023-05-04 at 9 04 27 PM](https://user-images.githubusercontent.com/6654625/236359495-8e1ed689-20e6-4428-80bd-c4e37cc7051f.png)
![Screenshot 2023-05-04 at 9 04 11 PM](https://user-images.githubusercontent.com/6654625/236359497-37be3cf9-2aa4-4b6f-a2d3-0c0f432c6ac6.png)

**Comment by dKosarevsky** [comment]
try to get last repo version
