### ISSUE TITLE
ChatCompletin method no longer supported by openai

### ISSUE THREAD

**Issue by aldonetti** [dKosarevsky/AI-Talks#60]
exception <<...You tried to access openai.ChatCompletion, but this is no longer supported in openai>=1.0.0 ...>> at line 15 of chat_gpt.py >> completion = openai.ChatCompletion.create(...

**Comment by data-if** [comment]
yep, in dev brnach you can find actual project version, but thanks

**Comment by dKosarevsky** [comment]
Its true, and you can find actual version of project in [dev](https://github.com/dKosarevsky/AI-Talks/tree/dev) branch
