### ISSUE TITLE
Disable auto generate audio answer

### ISSUE THREAD

**Issue by first-leon** [dKosarevsky/AI-Talks#9]
Возможно имеет смысл отключить автоматическую генерацию аудио ответа. Лучше выбор сделать, "Тип вывода": "Аудио", "Аудио и текст", "Только текст".
Мне, например, аудио не нужно, а гугловый АПИ зря дергается. Думаю не мне одному требуется только текст.

It may make sense to disable the automatic generation of the audio response. It is better to make a choice, "Output type": "Audio", "Audio and text", "Text only".
For example, I don't need audio, and the Google API is twitching in vain. I think I'm not the only one who needs only the text.

**Comment by dKosarevsky** [comment]
Реализована лаконичный вариант взаимодействия с API https://github.com/dKosarevsky/AI-Talks/commit/1470a903a22008975c7a249b8f7c6e10357e788a в ветке [dev](https://github.com/dKosarevsky/AI-Talks/tree/dev)
